name: Deploy to Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Telecomunicaciones-G-Network/portal-cliente3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/qa.portal.app/portal-cliente3
            git pull origin main
            npm install --force
            ng build
            rm -rf /var/www/deploy-portal/*
            mv ./dist/* /var/www/deploy-portal/
            sudo systemctl restart apache2
