name: Deploy to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Telecomunicaciones-G-Network/portal-cliente3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SV_HOST }}
          port: ${{ secrets.DO_SV_PORT }}
          username: ${{ secrets.DO_SV_USER }}
          key: ${{ secrets.DO_SV_PRIVATE_KEY }}
          script: |
            cd /var/www/html/portal-cliente3
            git pull origin main
            npm install --force
            ng build
            sudo systemctl restart apache2
